name: Update Packages

on:
  repository_dispatch:
    types: [update-packages]

jobs:
  update-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Add npm package
        run: yarn add @polybase/client @polybase/eth @polybase/react @polybase/util

      - name: Get latest version
        id: version
        run: |
          latest_version=$(npm show @polybase/client version)
          echo "::set-output name=latest__version::$latest__version"

      - name: Create a PR  # Action will update PR automatically if it already exists
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
          title: Update packages to version ${{ steps.version.outputs.latest__version }}
          branch: update-packages
          delete-branch: true
          base: main
          team-reviewers: engineering